### ISSUE TITLE
Connection issue and crash

### ISSUE THREAD

**Issue by prototype464** [LordAkkarin/Beacon#24]
After opening the 25565 port on Minecraft: Java Edition and playing with some friends, anyone can connect the first time, but when one of them leaves, they can't reconnect until Beacon is restarted. Beacon also freezes when clicking "Close Ports".

**Reproduction Steps**
Describe the steps to reproduce the behavior:
1. Start the MC server and Beacon
2. Open the 25565 port for Minecraft: Java Edition
3. Have a friend (not from a local machine) connect and then disconnect. They will be unable to join a 2nd time.
3.1. Trying to close the port will just cause Beacon to freeze after someone has already connected and disconnected

**Expected Behavior**
Beacon doesn't crash when clicking "Close Ports" and players should be able to reconnect normally.

**Screenshots**
N/A

**Environment (please complete the following information):**
 - OS: Windows 10 Pro
 - Application Version: 3.0.0-alpha.1 - 3.0.0-alpha.3

**Additional Context**
N/A

**Comment by dotStart** [comment]
Please provide logs as outlined in [the documentation](http://dotstart.github.io/Beacon/docs/troubleshooting/logs.html). Without them it'll be impossible to tell what went wrong exactly.

However, I can already tell you that Beacon has absolutely no way of telling whether players connect or not. It simply requests a port forwarding from your router and refreshes it every couple of seconds.
