### ISSUE TITLE
[FEATURE] Offline mode

### ISSUE THREAD

**Issue by huzpsb** [LordAkkarin/Beacon#37]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I'm always frustrated when trying to use it for CTFs.

**Describe the solution you'd like**
Use it without the internet.
**Describe alternatives you've considered**

**Additional context**

**Comment by dotStart** [comment]
Sorry, but I don't see how an offline mode makes sense for Beacon. It is specifically meant to allow less technically inclined users to open ports to the internet for the purposes of hosting game servers. Nothing more, nothing less.

It really isn't suited for any sort of pentesting or similar activities and frankly will never serve those kinds of purposes. It's simply designed for a different audience. There are more than likely already CLI tools that do a much better job at providing direct access to the protocol (and they're probably already part of the usual suites).
