### ISSUE TITLE
Log4j issue when scanning

### ISSUE THREAD

**Issue by AsgerD1000** [LordAkkarin/Beacon#46]
**Reproduction Steps**
go to virus total and scan the release v3.0.0-alpha.2

**Screenshots**
![image](https://github.com/user-attachments/assets/fd57caab-4222-4b2f-88f8-52e3e8eb6c8a)
![image](https://github.com/user-attachments/assets/48ad271c-cfd3-46fc-ae24-d55134123cc6)

**Environment:**
 - Application Version: v3.0.0-alpha.2

**Additional Context**
i want to know if it can be fixed i wont risk it for myself

**Comment by dotStart** [comment]
I no longer maintain this project. It's provided as-is with whatever issues it had at the time of the last release.

That being said: Technically the application ships with a vulnerable version of Log4j. The circumstances in which somebody would be able to abuse this are so convoluted though that you'd likely have way bigger issues at that point (for one the attacker would need to be in your local network).

So TL;DR: Use it as-is, or don't.
